# constants.py

MIN_CONNECTION_TIME = 0
MAX_CONNECTION_TIME = 5
MIN_TRAIN_TIME = 0
MAX_TRAIN_TIME = 90
NUM_CLIENTS = 40
NUM_UPDATES = 80
TIMEOUT = 8
LOCAL_EPOCHS = 1
BATCH_SIZE = 32
PERCENTILE_LIST = [25, 50, 75]